-- Insert initial products from intru.in
INSERT OR IGNORE INTO products (id, name, slug, description, price, original_price, image_url, image_url_2, category, is_featured, is_active, stock) VALUES 
  (1, 'Doodles T-Shirt', 'doodles-tshirt', 'A stylish t-shirt with unique doodle prints. Perfect for everyday wear with a touch of minimalism.', 999.00, 1499.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05839_1.jpg?v=1730301823', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05836.jpg?v=1730301823', 'T-Shirts', 1, 1, 100),
  (2, 'No Risk Porsche T-Shirt', 'porsche-tshirt', 'Bold and edgy Porsche-themed t-shirt. Show your love for speed and style.', 999.00, 1499.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05927_2.jpg?v=1730301907', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05923.jpg?v=1730301907', 'T-Shirts', 1, 1, 100),
  (3, 'Orange Puff Printed T-Shirt', 'orange-puff-tshirt', 'Vibrant orange t-shirt with unique puff printing. Stand out with this eye-catching design.', 999.00, 1499.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05910_3.jpg?v=1730301968', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05909.jpg?v=1730301968', 'T-Shirts', 0, 1, 100),
  (4, 'Romanticise Crop Tee', 'romanticise-crop-tee', 'Chic crop tee for the modern minimalist. Perfect for creating effortless everyday style.', 699.00, 999.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05883.jpg?v=1730301994', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05877.jpg?v=1730301994', 'Tops', 1, 1, 100),
  (5, 'Stripe 18 Shirt', 'stripe-18-shirt', 'Classic striped shirt with a contemporary twist. Versatile piece for any wardrobe.', 1099.00, 1699.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05899.jpg?v=1730302024', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05895.jpg?v=1730302024', 'Shirts', 0, 1, 100),
  (6, 'Summer Shirt', 'summer-shirt', 'Light and breezy summer shirt. Your go-to for casual summer days.', 999.00, 1599.00, 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05865.jpg?v=1730302047', 'https://cdn.shopify.com/s/files/1/0622/3628/2180/files/DSC05862.jpg?v=1730302047', 'Shirts', 0, 1, 100);

-- Insert default admin user (password would need to be hashed in production)
INSERT OR IGNORE INTO users (id, email, name, provider, is_admin) VALUES 
  (1, 'admin@intru.in', 'Admin', 'email', 1);

-- Insert default pages
INSERT OR IGNORE INTO pages (slug, title, content, meta_title, meta_description, is_active) VALUES 
  ('brand-story', 'Our Brand Story', 
   '# Welcome to INTRU\n\nBuilt from scratch with a shared love for minimalism & everyday style.\n\nAt INTRU, we believe that fashion should be effortless, timeless, and accessible. Our journey began with a simple idea: to create clothing that embodies minimalist aesthetics while celebrating individuality.\n\n## Our Philosophy\n\nWe design pieces that transcend trends and seasons. Each item in our collection is carefully crafted to be versatile, comfortable, and stylish - perfect for the modern lifestyle.\n\n## Sustainability\n\nWe are committed to sustainable practices, from sourcing materials to production. Every piece is made with care for both people and the planet.\n\n## Join Our Community\n\nWhen you choose INTRU, you become part of a community that values quality, simplicity, and conscious living.',
   'Our Brand Story - INTRU', 'Discover the story behind INTRU - built from scratch with a shared love for minimalism & everyday style', 1),
  
  ('terms-and-conditions', 'Terms and Conditions', 
   '# Terms and Conditions\n\nLast updated: February 2026\n\n## 1. Introduction\n\nWelcome to INTRU. These terms and conditions outline the rules and regulations for the use of our website and services.\n\n## 2. Acceptance of Terms\n\nBy accessing this website, we assume you accept these terms and conditions. Do not continue to use INTRU if you do not agree to all of the terms and conditions stated on this page.\n\n## 3. Products and Services\n\n- All products are subject to availability\n- We reserve the right to limit quantities\n- Prices are subject to change without notice\n\n## 4. Orders and Payment\n\n- Orders are subject to acceptance and availability\n- Payment is processed securely through Razorpay\n- You will receive order confirmation via email\n\n## 5. Intellectual Property\n\nThe content, design, and branding on this website are owned by INTRU and protected by copyright laws.\n\n## 6. Limitation of Liability\n\nINTRU shall not be liable for any indirect, incidental, or consequential damages arising from the use of our products or services.\n\n## 7. Changes to Terms\n\nWe reserve the right to modify these terms at any time. Please review this page periodically.\n\n## Contact Us\n\nFor any questions regarding these terms, please contact us at support@intru.in',
   'Terms and Conditions - INTRU', 'Read our terms and conditions for using INTRU website and services', 1),
  
  ('privacy-policy', 'Privacy Policy', 
   '# Privacy Policy\n\nLast updated: February 2026\n\n## 1. Information We Collect\n\nWe collect information that you provide directly to us:\n- Name and email address\n- Shipping and billing information\n- Payment information (processed securely via Razorpay)\n- Order history and preferences\n\n## 2. How We Use Your Information\n\nWe use the information we collect to:\n- Process your orders and payments\n- Send order confirmations and updates\n- Provide customer support\n- Send marketing communications (with your consent)\n- Improve our products and services\n\n## 3. Information Sharing\n\nWe do not sell or rent your personal information to third parties. We may share information with:\n- Payment processors (Razorpay) for transaction processing\n- Shipping partners for order fulfillment\n- Service providers who assist our operations\n\n## 4. Data Security\n\nWe implement appropriate security measures to protect your personal information. However, no method of transmission over the internet is 100% secure.\n\n## 5. Cookies\n\nWe use cookies to enhance your browsing experience and remember your preferences.\n\n## 6. Your Rights\n\nYou have the right to:\n- Access your personal information\n- Correct inaccurate data\n- Request deletion of your data\n- Opt-out of marketing communications\n\n## 7. Third-Party Authentication\n\nWhen you sign in using Google or Instagram, we receive basic profile information as permitted by those services. We do not store your passwords.\n\n## 8. Changes to Privacy Policy\n\nWe may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page.\n\n## Contact Us\n\nFor privacy-related questions, contact us at privacy@intru.in',
   'Privacy Policy - INTRU', 'Learn how INTRU collects, uses, and protects your personal information', 1),
  
  ('return-and-exchange', 'Return & Exchange Policy', 
   '# Return & Exchange Policy\n\n## Easy Returns & Exchanges\n\nAt INTRU, we want you to love your purchase. If you''re not completely satisfied, we offer hassle-free returns and exchanges.\n\n## Return Policy\n\n### Eligibility\n- Items must be returned within 7 days of delivery\n- Products must be unworn, unwashed, and in original condition\n- Original tags must be attached\n- Items must be in original packaging\n\n### Non-Returnable Items\n- Sale items marked as "Final Sale"\n- Items damaged due to misuse\n- Products without original tags\n\n## Exchange Policy\n\n### Size Exchanges\n- Free size exchanges within 7 days\n- Item must be in original condition\n- Subject to availability\n\n### How to Exchange\n1. Contact us at support@intru.in\n2. Provide order number and reason for exchange\n3. We''ll arrange pickup and send replacement\n\n## Refund Process\n\n### Timeline\n- Refunds processed within 5-7 business days after receiving returned item\n- Amount will be credited to original payment method\n- You will receive email confirmation\n\n### Refund Amount\n- Full refund for defective or incorrect items\n- Shipping charges non-refundable (unless item is defective)\n\n## How to Initiate Return\n\n1. Email us at support@intru.in with:\n   - Order number\n   - Item(s) you wish to return\n   - Reason for return\n   - Photos (if item is defective)\n\n2. We''ll send return instructions within 24 hours\n\n3. Pack the item securely with original tags and invoice\n\n4. We''ll arrange pickup from your address\n\n## Defective or Wrong Items\n\nIf you receive a defective or incorrect item:\n- Contact us immediately\n- Send photos of the issue\n- We''ll arrange free pickup and send replacement\n- Full refund including shipping if replacement unavailable\n\n## Contact Us\n\nFor any questions about returns or exchanges:\n- Email: support@intru.in\n- Response time: Within 24 hours\n\n*This policy is subject to change. Please check this page for updates.*',
   'Return & Exchange Policy - INTRU', 'Easy returns and exchanges within 7 days. Learn about our hassle-free return policy', 1);
